### ISSUE TITLE
UIViewReportBrokenSuperviewChain

### ISSUE THREAD

**Issue by fangnow** [nativex/NativeX-iOS-SDK#3]
I'm passing our my window's root view controller in the delegate callback and keep seeing this 

`*** Assertion failure in void UIViewReportBrokenSuperviewChain(UIView *__strong, UIView *__strong, BOOL)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3599.6.1/UIView.m:190
2016-10-17 18:19:43.683389 TextNow-Free[717:124431] +[NativeXSDK showAdWithName:andShowDelegate:fetchNowIfNeeded:rootViewController:]:2782 - caught exception:NSInternalInconsistencyException, reason:View has lost track of its superview, most likely through unsupported use of CALayer API on the view's layer. If this isn't a crash yet, it will be in the near future. 
	Problem view: <UIWebOverflowScrollView: 0x10517a200; frame = (0 0; 568 568); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x17465ffb0>; layer = <WebLayer: 0x170628980>; contentOffset: {0, 0}; contentSize: {568, 4030}>
	Expected parent: <UIWebBrowserView: 0x104993600; frame = (0 0; 0 0); text = 'Get Free Credits (cents)!...'; opaque = NO; gestureRecognizers = <NSArray: 0x170653ad0>; layer = <UIWebLayer: 0x170434ea0>>
Break on UIViewReportBrokenSuperviewChain to debug.`

I do as much and breakpoint on UIViewReportBrokenSuperviewChain, and the view hierarchy seems to expect a UIWebView? But there is no webview and steps between calling NativeX and this exception.

![screen shot 2016-10-17 at 6 13 32 pm](https://cloud.githubusercontent.com/assets/22302412/19461048/020e0f3c-9496-11e6-8c9a-46f2728d228b.png)

**Comment by werelord** [comment]
Send a message to engineering.support@nativex.com with your appid and placement name; this is an iOS subsystem bug that can be fixed with changes to your placement template.

**Comment by fangnow** [comment]
Will do I'll try that.
